/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.kamaleon.frenteDeLoja.biometria.login;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;

import br.com.kamaleon.frenteDeLoja.util.FuncoesSwingUtil;

/**
 *
 * @author Vinicius
 */
public class LoginBiometria_FL extends javax.swing.JFrame {

	LoginBiometria_Controller controller;
    /**
     * Creates new form LoginBiometria_FL
     */
    public LoginBiometria_FL() {
        initComponents();
        controller = new LoginBiometria_Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();
        textSenha = new javax.swing.JPasswordField();
        BotaoOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelBiometrica = new javax.swing.JLabel();
        labelVerificacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biometria");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 150, 60, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Login:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 60, 30);

        textLogin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLoginActionPerformed(evt);
            }
        });
        getContentPane().add(textLogin);
        textLogin.setBounds(70, 110, 210, 30);

        textSenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(textSenha);
        textSenha.setBounds(70, 150, 210, 30);

        BotaoOK.setText("OK");
        BotaoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOKActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoOK);
        BotaoOK.setBounds(100, 190, 100, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/kamaleon/frenteDeLoja/biometria/login/1294741536Empreinte.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 80, 110);

        labelBiometrica.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelBiometrica.setText("BIOMETRICA");
        getContentPane().add(labelBiometrica);
        labelBiometrica.setBounds(100, 50, 180, 50);

        labelVerificacao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelVerificacao.setText("VERIFICAÇÃO ");
        getContentPane().add(labelVerificacao);
        labelVerificacao.setBounds(100, 10, 180, 50);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-297)/2, (screenSize.height-254)/2, 297, 254);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOKActionPerformed
        
    	try {
    		controller.login();
    	} catch (Exception e) {
    		// TODO Auto-generated catch block
    		e.printStackTrace();
    		FuncoesSwingUtil.mostrarMensagemErro(this, "Erro", e.getMessage());
    	}
    	
    }//GEN-LAST:event_BotaoOKActionPerformed

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        
    	try {
    		controller.login();
    	} catch (Exception e) {
    		// TODO Auto-generated catch block
    		e.printStackTrace();
    		FuncoesSwingUtil.mostrarMensagemErro(this, "Erro", e.getMessage());
    	}
    	
    }//GEN-LAST:event_textSenhaActionPerformed

    private void textLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLoginActionPerformed
       
    	textSenha.requestFocus();
    	
    }//GEN-LAST:event_textLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginBiometria_FL().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel labelBiometrica;
    protected javax.swing.JLabel labelVerificacao;
    protected javax.swing.JTextField textLogin;
    public javax.swing.JPasswordField textSenha;
    // End of variables declaration//GEN-END:variables
}
